name: 3ased05
description: No bloat AI-ready container-focused daily driver - the full 3ased05 experience
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/ubuntu-fonts/repo/fedora-%OS_VERSION%/atim-ubuntu-fonts-fedora-%OS_VERSION%.repo
    install:
      - copyq
      - gnome-tweaks
      - gnome-shell-extension-appindicator
      - dconf-editor
      - distrobox
      - git
      - vim
      - htop
      - neofetch
      - python3-pip
      - python3-virtualenv
      - pipx
      - tumbler
      - tumbler-extras
      - ffmpegthumbnailer
      - libinput-gestures
      - touchegg
      - podman-compose
      - docker-compose
      - usbguard
      - firejail
    remove:
      - steam
      - gamescope
      - gamemode
      - mangohud
      - obs-studio-plugin-vkcapture

  - type: files
    files:
      - source: files/branding/wallpapers/default.jpg
        destination: /usr/share/backgrounds/3ased05/default.jpg
      - source: files/branding/plymouth/splash.jpg
        destination: /usr/share/plymouth/themes/3ased05/splash.jpg
      - source: files/branding/grub/background.jpg
        destination: /boot/grub2/themes/3ased05/background.jpg
      - source: files/scripts/based05-setup-workspaces.sh
        destination: /usr/local/bin/based05-setup-workspaces.sh

  - type: systemd
    system:
      enabled:
        - usbguard.service
